steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/<GAR-PROJECT-ID>/compress-clean-container:latest', '.']
images:
- 'gcr.io/<GAR-PROJECT-ID>/compress-clean-container:latest'
